disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name

opt_in_rules:
  - attributes
  - empty_count
  - explicit_init

included:
  - Source
  - Tests

excluded:
  - Carthage
  - Pods
  - DerivedData

reporter: "xcode"
